connection_str = "DefaultEndpointsProtocol=https;AccountName=videoimageextract;AccountKey=HCOVTQPTNDJU0rgJqEPcO39iFP8K0ORAieqjGWaR1R0jailpn5jSWkSiuYXras0Suo8MtzpK7egl+AStuTf8Nw==;EndpointSuffix=core.windows.net"
